package config

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteDefaultCreatesFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "parser.yaml")

	got, err := WriteDefault(path, false)
	if err != nil {
		t.Fatal(err)
	}
	if got != path {
		t.Fatalf("path=%q want %q", got, path)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	body := string(data)
	for _, want := range []string{
		"Generated by: project-parser config init",
		"scan:",
		"plugins:",
		"report:",
		"graph:",
		"log:",
	} {
		if !strings.Contains(body, want) {
			t.Fatalf("missing %q in:\n%s", want, body)
		}
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	if loaded.Log.Level != "info" {
		t.Fatalf("log.level=%q", loaded.Log.Level)
	}
}

func TestWriteDefaultRefusesOverwrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "parser.yaml")
	if _, err := WriteDefault(path, false); err != nil {
		t.Fatal(err)
	}
	_, err := WriteDefault(path, false)
	if !errors.Is(err, ErrConfigExists) {
		t.Fatalf("got %v want ErrConfigExists", err)
	}
}

func TestWriteDefaultForceOverwrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "parser.yaml")
	if err := os.WriteFile(path, []byte("old"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := WriteDefault(path, true); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "scan:") {
		t.Fatalf("unexpected content: %s", data)
	}
}

func TestWriteDefaultEmptyPathUsesParserYAML(t *testing.T) {
	dir := t.TempDir()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(wd) })
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}

	got, err := WriteDefault("", false)
	if err != nil {
		t.Fatal(err)
	}
	if got != "parser.yaml" {
		t.Fatalf("got %q", got)
	}
}
