package config

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// ErrConfigExists is returned when init refuses to overwrite an existing file.
var ErrConfigExists = errors.New("config file already exists")

const initHeader = `# project-parser configuration
# Generated by: project-parser config init
#
# Docs: https://github.com/FiaLDI/project-parse

`

// WriteDefault writes the default configuration to path.
// If path is empty, parser.yaml in the current directory is used.
// Unless force is true, an existing file is not overwritten.
func WriteDefault(path string, force bool) (string, error) {
	if path == "" {
		path = "parser.yaml"
	}
	path = filepath.Clean(path)

	if !force {
		if _, err := os.Stat(path); err == nil {
			return "", fmt.Errorf("%w: %s (use --force to overwrite)", ErrConfigExists, path)
		} else if !os.IsNotExist(err) {
			return "", fmt.Errorf("stat config: %w", err)
		}
	}

	cfg := Default()
	body, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("marshal config: %w", err)
	}

	var out bytes.Buffer
	out.WriteString(initHeader)
	out.Write(body)

	dir := filepath.Dir(path)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", fmt.Errorf("create config dir: %w", err)
		}
	}

	if err := os.WriteFile(path, out.Bytes(), 0o644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}
	return path, nil
}
